# Generated by Django 3.2.4 on 2021-06-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=500)),
                ('Plan', models.CharField(max_length=500)),
                ('DateOfJoining', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=500)),
                ('SetupBoxNumber', models.CharField(max_length=500)),
                ('LastPaymentDate', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('PaymentId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.CharField(max_length=500)),
                ('DateOfPayment', models.CharField(max_length=500)),
                ('PaidAmount', models.CharField(max_length=500)),
            ],
        ),
    ]
